"""add otp code to User model

Revision ID: 631ebd6e48c0
Revises: 04f62ac1044a
Create Date: 2026-02-13 06:55:55.865819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631ebd6e48c0'
down_revision: Union[str, Sequence[str], None] = '04f62ac1044a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
